name: Issue Review

on:
  issues:
    types: [opened]
permissions:
  issues: write
  contents: read
jobs:
  review_issue:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install openai
        pip install PyGithub
        pip install qdrant-client
        pip install regex

    - name: Review Issue with LLM
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        QD_API_KEY: ${{ secrets.QD_API_KEY }}
        QD_URL: ${{ secrets.QD_URL }}
      run: |
        python review_issue.py
